Subtract the 1D Array *arr2* from the 2D array *arr1*, such that each item of *arr2* subtracts from respective row of *arr1*

Ex

arr1 = `[[x1, x2 , x3], [y1, y2, y3], [z1,z2,z3]]`

arr2 = `[x,y,z]`

Result `[ [ x1-x, x2-x, x3-x],` etc

In [9]:
import numpy as np

arr1 = np.arange(9).reshape(3,3)
arr2 = np.arange(3)
final = np.empty(9).reshape(3,3)

# print(arr1)
# print(arr2)
# print(arr3)

for i in range(arr1.shape[0]):
    for j in range(arr1.shape[1]):
        final[i][j] = arr1[i][j] - arr2[i]
        
print(final)       

for i in range(len(arr2)):
    arr1[i] = arr1[i] - arr2[i]
    
print(arr1)

[[0. 1. 2.]
 [2. 3. 4.]
 [4. 5. 6.]]
[[0 1 2]
 [2 3 4]
 [4 5 6]]


Given a 1D Array, find the local maxima (numbers surrounded by 2 smaller numbers)

In [18]:
arr3 = np.array([10, 2, 12, 4, 5, 1, 7, 8, 9, 6, 11])

#print(arr3[0]-2) 
for i in range(1,arr3.shape[0]-1):
    if arr3[i] > arr3[i-1] and arr3[i] > arr3[i+1]:
        print(arr3[i])

12
5
9


Given two n x m Arrays, compute the average of elements in matching subarrays

Ex

arr1      
`[[1,1],[2,2],[3,3]]`

arr2      
`[[1,1],[2,2],[3,3]]`

result:
`[1,2,3]`

or

Ex

arr1      
`[[3,3],[2,2],[10,10]]`

arr2      
`[[1,1],[2,2],[3,3]]`

result:
`[2,2,6.5]`

In [23]:
a1 = np.array(([1,1],[2,2],[3,3]))
a2 = np.array(([3,3],[2,2],[10,10]))
a3 = np.zeros(3)
#(sum(a1[0]) + sum(a2[0]))/ (len(a1[0])*2)
for i in range(3):
    a3[i] = (sum(a1[i]) + sum(a2[i]))/ (len(a1[i])*2)
    
a3

array([2. , 2. , 6.5])